services:
  - type: web
    name: mypro
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You will set this manually in the dashboard
